
import java.util.Arrays;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Notebook
 */
public class JanelaVetores extends javax.swing.JFrame {
    String vetor[] = new String[10];
    int selecionado = 0;
    DefaultListModel lista = new DefaultListModel();
    public JanelaVetores() {
        initComponents();
        Arrays.fill(vetor, " ");
        for (String vm: vetor){
            lista.addElement(vm);
        }
        String vetor[] = new String[lista.size() ];
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspValor = new javax.swing.JSpinner();
        jbtnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jbtnRemover = new javax.swing.JButton();
        jbtnOrdernar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlblSelecionado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblTamanho = new javax.swing.JLabel();
        jbtnAdicionarPos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jspValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jspValor.setModel(new javax.swing.SpinnerNumberModel());

        jbtnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAdicionar.setText("Adicionar");
        jbtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarActionPerformed(evt);
            }
        });

        jList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList.setModel(lista);
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jbtnRemover.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnRemover.setText("Remover");
        jbtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverActionPerformed(evt);
            }
        });

        jbtnOrdernar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnOrdernar.setText("Ordernar");
        jbtnOrdernar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrdernarActionPerformed(evt);
            }
        });

        jLabel1.setText("Vetor:");

        jlblSelecionado.setText("0");

        jLabel2.setText("Posições totais:");

        jlblTamanho.setText("10");

        jbtnAdicionarPos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnAdicionarPos.setText("Adicionar");
        jbtnAdicionarPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarPosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jspValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnOrdernar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnAdicionarPos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTamanho))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblSelecionado)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblSelecionado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jbtnAdicionar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnRemover)
                            .addComponent(jspValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnOrdernar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdicionarPos)
                    .addComponent(jLabel2)
                    .addComponent(jlblTamanho))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //Ação de adicionar
    private void jbtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarActionPerformed
        System.out.println(lista.size());
        int selecionado = jList.getSelectedIndex();
        if (selecionado < lista.size() && selecionado >= 0){
            vetor[selecionado] = Integer.toString((int) jspValor.getValue());
            lista.removeAllElements();
            for (String vm: vetor){
                lista.addElement(vm);
            }
        }else{
        //nada
        }
    }//GEN-LAST:event_jbtnAdicionarActionPerformed
    //"Remover" elemento da posição
    private void jbtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverActionPerformed
        int selecionado = jList.getSelectedIndex();
        lista.set(selecionado, " ");
    }//GEN-LAST:event_jbtnRemoverActionPerformed

    private void jbtnOrdernarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrdernarActionPerformed
        Integer inteiro[] = new Integer[lista.size()]; //Variável criada para ordenar a String vetor[]
        //Conversor de String para int dos valores
        for (int c = 0; c< lista.size(); c++){
                if (vetor[c].isBlank()){
                    vetor[c] = "2147483647";
                }
                inteiro[c] = Integer.parseInt(vetor[c]);
        }
        //Ordenamneto dos valores
        Arrays.sort(inteiro);
        //Reconversor de int para String (para colocar na lista)
        for (int c = 0; c<lista.size(); c++){
            if (inteiro[c] != 2147483647){
            vetor[c] = Integer.toString(inteiro[c]);
            }else{
                vetor[c] = " ";
            }
        }
        //Adiciona a lista novamente
        lista.removeAllElements();
        for (String vm:vetor){
            lista.addElement(vm);
        }
    }//GEN-LAST:event_jbtnOrdernarActionPerformed

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        //Pega o índice do vetor
        int selecionado = jList.getSelectedIndex();
        jlblSelecionado.setText(Integer.toString(selecionado + 1));
    }//GEN-LAST:event_jListMouseClicked

    private void jbtnAdicionarPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarPosActionPerformed
        lista.addElement(" ");
        jlblTamanho.setText(Integer.toString(lista.size()));
    }//GEN-LAST:event_jbtnAdicionarPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVetores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdicionar;
    private javax.swing.JButton jbtnAdicionarPos;
    private javax.swing.JButton jbtnOrdernar;
    private javax.swing.JButton jbtnRemover;
    private javax.swing.JLabel jlblSelecionado;
    private javax.swing.JLabel jlblTamanho;
    private javax.swing.JSpinner jspValor;
    // End of variables declaration//GEN-END:variables
}
